import { InMemoryDbService } from 'angular-in-memory-web-api';
import { IGroup, IReceipt } from './constants/models';

export class ReceiptInMemDataService implements InMemoryDbService {
  createDb() {
    const receipts: IReceipt[] = [
      {
        id: 'idalkjdgausgd771gyu2g3u',
        subtotal: 13,
        total: 13.13,
        tax: 0.13,
        date: '2019-05-13T19:07:05.000Z',
        store: 'store',
        userId: 'userId',
        groupId: 'groupId',
        payer: 'payer',
        list: [
          {
            id: '085119900102',
            name: '5 Gal Primo Water Exchange',
            price: 6.50,
            image: 'http://identitystandards.illinois.edu/assets/images/i_mark_bold.png',
            people: [],
          },
          {
            id: '085119900102',
            name: '5 Gal Primo Water Exchange',
            price: 6.50,
            image: 'http://identitystandards.illinois.edu/assets/images/i_mark_bold.png',
            people: [],
          },
        ],
        people: [
          {
            name: 'emily',
            selection: false,
            price: 3.2,
            isDriver: true,
            isPassenger: true,
          },
          {
            name: 'jake',
            selection: false,
            price: 12.2,
            isDriver: true,
            isPassenger: true,
          },
          {
            name: 'evelyn',
            selection: false,
            price: 5,
            isDriver: true,
            isPassenger: true,
          },
        ],
      },
      {
        id: '5cfd4bc48593400010c327e7',
        userId: '5c626df3d8106f00160dde3f',
        groupId: 'groupId',
        list: [
          {
            id: '003700090731',
            name: 'Crest + Deep Clean Complete Whitening Toothpaste, Effervescent Mint, 5.4 oz, Pack of 2',
            price: 4.97,
            image: 'https://i5.walmartimages.com/asr/50b00633-b6ac-48db-96f4-e5e64e3a42b1_1.b204bc7a800e18f42aeb6df271fede5e.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 4.97,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '003663202753',
            name: 'Oikos Plain Greek Nonfat Yogurt, 32 oz',
            price: 4.33,
            image: 'https://i5.walmartimages.com/asr/d94afd04-6c44-4c7c-ac2f-5ec149631d7b_1.0bea85e8a8331913f4a089294a6341c8.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 4.33,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '003338366604',
            name: 'Peeled Baby-Cut Carrots, 2 lbs',
            price: 1.84,
            image: 'https://i5.walmartimages.com/asr/e493b000-a365-4d9c-a8da-59b3055c6913_1.36a66eee90b3fbe874f56972d8285dac.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 0.92,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: true,
                price: 0.92,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '4aba6a58-6c5d-476f-816a-1739b08e6758',
            name: 'BULK PEARs OOOOOOOO4413KF 0.84 lb @ 1 lb /1.47 1.23 R',
            price: 1.23,
            image: 'http://identitystandards.illinois.edu/assets/images/i_mark_bold.png',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 1.23,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '9417f74f-663e-496a-82af-3e513580c4aa',
            name: 'BNLS CK BRST',
            price: 6.77,
            image: 'http://identitystandards.illinois.edu/assets/images/i_mark_bold.png',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 6.77,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '000000004011',
            name: 'Bananas, each',
            price: 1.13,
            image: 'https://i5.walmartimages.com/asr/209bb8a0-30ab-46be-b38d-58c2feb93e4a_1.1a15fb5bcbecbadd4a45822a11bf6257.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 0.565,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: true,
                price: 0.565,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '068113110523',
            name: 'Equate Fresh Scent Flushable Wipes, 3 pack, 144 count',
            price: 3.97,
            image: 'https://i5.wal.co/asr/c00d1575-0117-46b5-8111-2e63849dea9b_1.389edd69f3070d5ac16fdaf02f2021e0.jpeg-729215735ba19152275ec182753c2d78d62f86cd-optim-2365x2365.jpg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 3.97,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '007052407548',
            name: 'Toilet Paper, 4 Rolls',
            price: 0.68,
            image: 'https://i5.wal.co/asr/157453bd-3f5e-42ca-ac53-c89b6b328e14_1.572825501214e6c5e3d4a8dbce6ac36f.jpeg-a1d05e69bf2e3b88b2a247e20eb443c86c78ef92-optim-350x350.jpg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 0.68,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '000000003082',
            name: 'Broccoli Crowns',
            price: 1.58,
            image: 'https://i5.walmartimages.com/asr/cfb40fdc-b31f-4f03-8823-e3b9bfedba45_1.032713d02198d33a625958b9a6e1dcff.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 1.58,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '075166677605',
            name: 'NatureSweet NatureSweet Tomatoes, 24 oz',
            price: 4.94,
            image: 'https://i5.walmartimages.com/asr/8b2a24e0-6f71-4cfe-aeb9-d34d443ced52_1.c6d5210d1cedbc588ad3970d625616f8.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 4.94,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '068113105673',
            name: 'Spring Valley Melatonin Tablets, 5 mg, 120 Ct, 2 Pk',
            price: 6.88,
            image: 'https://i5.walmartimages.com/asr/1f08481a-6b9c-4a87-bc8a-3fbcd5e7e661_1.c46ed45f0d4f6770e602afc743bd2e77.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '007050105021',
            name: 'Neutrogena Deep Clean Invigorating Foaming Face Scrub, 4.2 fl. oz',
            price: 6.67,
            image: 'https://i5.walmartimages.com/asr/ca4eccdc-67e1-4de6-8b2f-b6233fd49733_1.64dcd5480610c073369e6d1ca1c1bbf0.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: true,
                price: 6.67,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '9332de56-ffe5-43b0-b3c1-88d5fc85d07e',
            name: 'BNLS CK BRST',
            price: 6.34,
            image: 'http://identitystandards.illinois.edu/assets/images/i_mark_bold.png',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 6.34,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '001410008599',
            name: 'Pepperidge Farm Whole Grain 100% Whole Wheat Bread, 24 oz. Bag',
            price: 2.98,
            image: 'https://i5.walmartimages.com/asr/323d38a3-a15c-416c-8d5f-88c91902d5b5_1.f542bf29a54c4c02f362817ccf7ed72d.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 2.98,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '068113116517',
            name: 'Equate Mango & Coconut Water Liquid Hand Soap, 7.5 fl oz',
            price: 0.75,
            image: 'https://i5.walmartimages.com/asr/c31c8dfe-7516-4f4b-bdd5-45ed7af0e66e_1.8a69a5b69d362c4873d5f633899f9497.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 0.75,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '001370011820',
            name: 'Hefty Red Plastic Party Cups, 18 Ounces, 20 Cups',
            price: 2.14,
            image: 'https://i5.walmartimages.com/asr/fbd188c2-7e46-4ce1-be43-8daf2b425f8e_1.5fa7b4de44299a874668ee8075b5e089.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: true,
                price: 2.14,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '003869876499',
            name: 'Mainstays Taza Nylon Rug, Multi-Color, 1\'6" x 2\'6"',
            price: 4.88,
            image: 'https://i5.walmartimages.com/asr/e8173515-3494-4c34-b1bd-3e6685ddb65e_1.cb96844bb8ee1fb4f6a8c75f695cc592.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: true,
                price: 4.88,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '007874227909',
            name: 'Great Value Purified Drinking Water, 16.9 Fl. Oz., 40 Count',
            price: 3.56,
            image: 'https://i5.wal.co/asr/7685021d-02b2-4d4e-8c4d-34a9455335e0_1.5b495668c05a641b9dd1d1557cfca5a7.jpeg-ad14e82050f28d647ed8dbcc34fb93124e77c5c9-optim-3000x2282.jpg',
            people: [
              {
                name: 'Charlie',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: true,
                price: 0.89,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: true,
                price: 0.89,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: true,
                price: 0.89,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: true,
                price: 0.89,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
          {
            id: '001089266228',
            name: 'Better Homes & Gardens Thick & Plush Trusoft Nylon Bath Rug, 1 Each',
            price: 3.50,
            image: 'https://i5.walmartimages.com/asr/5e13b174-0639-4379-99b0-eba33921a4f4_1.b49a5b00b0fe4333024f903859a57a87.jpeg',
            people: [
              {
                name: 'Charlie',
                selection: true,
                price: 3.5,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Xinghan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Lawrence',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Mohan',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
              {
                name: 'Haowei',
                selection: false,
                price: 0,
                isDriver: false,
                isPassenger: false,
              },
            ],
          },
        ],
        people: [
          {
            name: 'Charlie',
            selection: false,
            price: 11.1,
            isDriver: false,
            isPassenger: false,
          },
          {
            name: 'Xinghan',
            selection: false,
            price: 41.495,
            isDriver: false,
            isPassenger: false,
          },
          {
            name: 'Lawrence',
            selection: false,
            price: 2.035,
            isDriver: false,
            isPassenger: false,
          },
          {
            name: 'Mohan',
            selection: false,
            price: 1.47,
            isDriver: false,
            isPassenger: false,
          },
          {
            name: 'Haowei',
            selection: false,
            price: 9.06,
            isDriver: false,
            isPassenger: false,
          },
        ],
        subtotal: 69.14,
        total: 72.04,
        tax: 2.9,
        date: '2019-06-09T12:46:59.000Z',
        store: 'walmart',
        payer: 'Feiyang ',
      },
    ];
    const groups: IGroup[] = [
      {
        id: 'adhuigduiw',
        name: 'group Alpha',
        people: ['charlie', 'emily', 'george'],
      },
      {
        id: 'asdo1j23',
        name: 'group beta',
        people: ['tim', 'sam', 'will'],
      },
    ];
    return {receipts, groups};
  }
}
